Repository gaeguul/ohmoney, pull requests merged in 2025-04, with the labels that each got.

#13 [Feat] #11 - db.json 생성
  src/config/db.json
  src/pages/account/AccountCreatePage.vue
  src/pages/account/accountAssets/AccountIcon.vue
  src/pages/account/accountAssets/accountFormIcon.js
Labels: feat

#15 [Feat] #2 - 홈 (캘린더) 페이지 UI/UX 구현
  src/assets/base.css
  src/assets/category.json
  src/assets/main.css
  src/components/calendar/CalendarHeader.vue
  src/components/calendar/CalendarTable.vue
  src/components/calendar/DailyAccount.vue
  src/pages/HomeVue.vue
  src/stores/useCalendarStore.js
Labels: feat

#17 [Feat] #3 - 가계부 내역 구현
  src/components/accounts/AccountDetailTable.vue
  src/components/accounts/AccountFilter.vue
  src/components/accounts/AccountHeader.vue
  src/pages/account/AccountListPage.vue
  src/pages/detail/DetailHistory.vue
Labels: feat

#14 [Feat] #5 - 월별 분석 구현
  package-lock.json
  package.json
  src/assets/base.css
  src/assets/main.css
  src/components/charts/IncomeExpenseChart.vue
  src/components/charts/MonthlyAnalysisChart.vue
  src/components/charts/MonthlySpendingChart.vue
  src/components/charts/ThreeMonthsAnalysisChart.vue
  src/components/charts/WeeklyAnalysisChart.vue
  src/pages/analysis/AnalysisDashboard.vue
Labels: feat

#20 [Feat] #3 - 가계부 내역 카테고리 필터 수정
  src/components/accounts/AccountFilter.vue
Labels: feat, chore

#26 [Feat] #21 - 가계부 내역 API 연동
  src/components/accounts/AccountDetailTable.vue
  src/components/accounts/AccountFilter.vue
  src/stores/categoryStore.js
  src/stores/filterStore.js
  src/stores/userStore.js
Labels: feat

#28 [Feat] #19 - 캘린더 페이지 api 연결
  src/assets/category.json
  src/assets/main.css
  src/components/calendar/CalendarHeader.vue
  src/components/calendar/CalendarTable.vue
  src/components/calendar/DailyAccount.vue
  src/pages/HomeVue.vue
  src/stores/useCalendarStore.js
Labels: feat

#32 [Feat] #22 - 월별 분석 API 연동
  src/api/analysis.js
  src/components/accounts/AccountDetailTable.vue
  src/components/charts/IncomeExpenseChart.vue
  src/components/charts/MonthlyAnalysisChart.vue
  src/components/charts/MonthlySpendingChart.vue
  src/components/charts/ThreeMonthsAnalysisChart.vue
  src/components/charts/WeeklyAnalysisChart.vue
  src/layouts/NavBar.vue
  src/main.js
  src/pages/analysis/AnalysisDashboard.vue
  src/pages/user/SigninView.vue
  src/pages/user/SignupView.vue
  src/router/index.js
  src/stores/analysisStore.js
Labels: feat

#46 [Feat] #35 카테고리별 분석 스타일 수정
  db.json
  src/components/charts/CategoryCircleChart.vue
  src/pages/analysis/AnalysisCategory.vue
  src/pages/analysis/CategoryGroup.vue
Labels: feat

#48 [Feat] #3 - 가계부 내역 테이블 색상 수정
  src/components/accounts/AccountDetailTable.vue
Labels: feat

#40 [Feat] #42 - 가계부 추가 form 연동
  db.json
  package-lock.json
  package.json
  src/pages/account/AccountCreatePage.vue
  src/pages/account/accountAssets/AccountIcon.vue
  src/pages/account/accountAssets/AccountIconGroup.vue
Labels: feat

#50 [Fix] #49 - 가계부 내역 기간 필터링 수정
  src/components/accounts/AccountDetailTable.vue
  src/pages/account/AccountEditPage.vue
  src/pages/account/accountAssets/AccountIcon.vue
  src/pages/account/accountAssets/AccountIconGroup.vue
Labels: fix

#51 Refactor #36 editForm, createForm 리팩토링
  db.json
  src/components/accounts/AccountDetailTable.vue
  src/components/accounts/AccountForm.vue
  src/components/accounts/accountAssets/AccountIcon.vue
  src/components/accounts/accountAssets/AccountIconGroup.vue
  src/pages/account/AccountCreatePage.vue
  src/pages/account/AccountEditPage.vue
Labels: refactor

#53 [Feat] #47 캘린더 오류 수정
  src/components/calendar/CalendarHeader.vue
  src/components/calendar/CalendarSummary.vue
  src/components/calendar/CalendarTable.vue
  src/components/calendar/DailyAccount.vue
  src/pages/HomeCalendar.vue
  src/pages/HomeVue.vue
  src/router/index.js
  src/stores/transactionStore.js
  src/stores/useCalendarStore.js
Labels: feat

#57 [Fix] #56 - 타이틀 수정 및 폰트 크기 작게 수정
  src/components/charts/WeeklyAnalysisChart.vue
Labels: fix, refactor

#54 [Chore] #52 - 프로젝트 배포
  vercel.json
  vite.config.js
Labels: chore
